# Generated by Django 5.2.1 on 2025-05-19 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('watts', models.FloatField(help_text='Power consumption in watts')),
                ('default_hours_per_day', models.FloatField(help_text='Typical usage time per day in hours')),
            ],
        ),
        migrations.CreateModel(
            name='SystemDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=5, help_text='Site latitude', max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, help_text='Site longitude', max_digits=8)),
                ('panel_watts', models.IntegerField(help_text='Recommended PV array wattage')),
                ('battery_ah', models.IntegerField(help_text='Recommended battery capacity (Ah)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Optional—link to Django user if you implement authentication', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_load_wh', models.FloatField(help_text='Total daily load in Wh')),
                ('sun_hours', models.FloatField(help_text='Average sun-hours/day')),
                ('panel_w', models.IntegerField(help_text='Calculated PV array wattage')),
                ('battery_ah', models.IntegerField(help_text='Calculated battery capacity (Ah)')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('system_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='sizing.systemdesign')),
            ],
        ),
    ]
